version: '3.5'

services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: serveurweb
    restart: always
    depends_on:
      - mariadb
    volumes:
      - ./sources/:/application
    ports:
      - "30000:80"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    ports:
      - '50000:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
  
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ilies
      - MYSQL_PASSWORD=aqwxsz